network/urls.py
from django.urls import path

from . import views

app_name = 'network'

urlpatterns = [
    path("", views.index, name="index"),
    path("index", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    
	# API Routes
    path("allPosts", views.allPosts, name="allPosts"),
    path("followedPeoplePosts", views.followedPeoplePosts, name="followedPeoplePosts"),
    path("posterPosts/<str:username>", views.posterPosts, name="posterPosts"),
    path("newPost", views.newPost, name="newPost"),
    path("like/<int:post_id>", views.likeUnlike, name = "likeUnlike"),
    path("follow/<str:username>", views.followUnfollow, name="folllowUnfollow"),
    path("updatePost", views.updatePost, name = "updatePost"),
    path("userSpace/<str:username>", views.userSpace, name="userSpace"),
    path("userInfo", views.userInfo, name="userInfo"),
]

project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("network/", include("network.urls")),
]

network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from datetime import datetime, time, date, timedelta, timezone

class User(AbstractUser):
    pass

class Post(models.Model):
	poster = models.ForeignKey(User, on_delete=models.CASCADE, related_name="poster")
	post = models.CharField(max_length=256)
	timestamp = models.DateTimeField(auto_now_add=True)
	
	def toJSON(self):
		return{
			"id": self.id,
			"user": self.poster.username,
			"content": self.post,
			"when": self.timestamp.strftime("%b %d %Y, %I:%M %p"),
		}

class Like(models.Model):
	post = models.ForeignKey(Post, on_delete = models.CASCADE, related_name="likedPost")
	liker = models.ForeignKey(User, on_delete = models.CASCADE, related_name="liker")

class Follow(models.Model):
	follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name="follower")
	personOfAttention = models.ForeignKey(User, on_delete=models.CASCADE, related_name="personOfAttention") # aka: the followed-one.

network/views.py
import json
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from datetime import datetime, time, date, timedelta, timezone

from .models import User, Post, Follow, Like

def index(request):
	return render(request, "network/index.html")

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("network:index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("network:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("network:index"))
    else:
        return render(request, "network/register.html")

def getPosts(peopleOfAttention, start, end):
	everything = []
	if len(peopleOfAttention) == 0:
		everything = Post.objects.all()
	else:
		for eachOne in peopleOfAttention:
			everything += Post.objects.filter(poster = eachOne)
	
	if end > len(everything):
		end = len(everything)
		
	chronList = []
	for eachOne in everything:
		chronList.append([eachOne, eachOne.timestamp.timestamp()])# creates a 2D list
	reverseChronList = sorted(chronList, key=lambda post: post[1], reverse = True)#... on which the list can get sorted (reverse) chronologically
	
	everything = []
	for x in range(start, end):
		everything.append(reverseChronList[x][0])#...then the post objects are being put back into their own list
	return everything
	
def allPosts(request):
	start = int(request.GET.get("start"))
	end = int(request.GET.get("end"))
	
	return JsonResponse([eachOne.toJSON() for eachOne in getPosts([],start,end)], status=200, safe=False)

@login_required	
def followedPeoplePosts(request):
	start = int(request.GET.get("start"))
	end = int(request.GET.get("end"))
	
	peopleOfAttention = []
	try:
		followObjects = Follow.objects.filter(follower = request.user)
		for people in followObjects:
			peopleOfAttention.append(people.personOfAttention)
	except(Follow.DoesNotExist, AttributeError):
		pass
	if len(peopleOfAttention) == 0:
		return JsonResponse({"message":"You're currently not following anyone."}, status=200)
	else:
		return JsonResponse([eachOne.toJSON() for eachOne in getPosts(peopleOfAttention, start, end)], status=200, safe=False)

def posterPosts(request, username):
	start = int(request.GET.get("start"))
	end = int(request.GET.get("end"))
	poster = User.objects.get(username = username)
	return JsonResponse([eachOne.toJSON() for eachOne in getPosts([poster],start,end)], safe=False)

@login_required	
def likeUnlike(request, post_id):
	post = Post.objects.get(id=post_id)
	liker = request.user
	action = str(request.GET.get("action"))
	
	if (action == "update"):
		try:
			likedPost = Like.objects.get(liker=liker, post=post)
			likedPost.delete()
			return JsonResponse({"message": "Like removed from DB"},status=200)
		except(Like.DoesNotExist, AttributeError):
			likedPost = Like(liker=liker, post=post)
			likedPost.save()
			return JsonResponse({"message": "Like saved to DB"},status=201)
	if (action == "read"):
		try:
			likedPost = Like.objects.get(liker=liker, post=post)
			return JsonResponse({"liked": True})
		except(Like.DoesNotExist, AttributeError):
			return JsonResponse({"liked": False})
	
@login_required	
def followUnfollow(request, username):
	followedOne = User.objects.get(username = username)
	follower = request.user
	
	message = None
	try:
		followObject = Follow.objects.get(follower = request.user, personOfAttention = followedOne)
		followObject.delete()
		message = "Not following anymore - removed from database."
	except (Follow.DoesNotExist, AttributeError):
		followObject = Follow(follower = request.user, personOfAttention = followedOne)
		followObject.save()
		message = "Now following - added to database."
	return JsonResponse({"message": message}, status=204)
		
@login_required	
@csrf_exempt		
def newPost(request):
	if request.method != "POST":
		return JsonResponse({"error": "POST request required."}, status=400)
        
	incoming = json.loads(request.body)
	content = incoming.get("content")
	if len(content) == 0:
		return JsonResponse({"error": "empty POST"}, status=400)
	
	p = Post(poster = request.user, post = content, timestamp = datetime.now(timezone.utc))
	p.save()
	return JsonResponse({"message": "Post placed successfully."}, status=201)

@login_required
@csrf_exempt
def updatePost(request):
	id = int(request.GET.get("post_id"))
	post = Post.objects.get(id = id)
	if request.method == "PUT":
		incoming = json.loads(request.body)
		post.post = incoming['content']
		post.save()
		return JsonResponse({"message": "Post updated."},status=204)

@csrf_exempt
def userSpace(request, username):
	personOfAttention = None
	if request.user.username == username:
		print("you're home")
		personOfAttention = request.user
	else:
		print("visiting someone else")
		try:
			personOfAttention = User.objects.get(username = username)
		except (User.DoesNotExist, AttributeError):
			return JsonResponse({'username': 'Does not exist.'},status=200) #or is it an error? it's just a fact.
	
	followingThisOne = None
	if request.user.is_anonymous is False and request.user.username != username:
		followingThisOne = False
		try:
			follow = Follow.objects.get(personOfAttention = personOfAttention, follower = request.user)
			followingThisOne = True
		except (Follow.DoesNotExist, AttributeError):
			pass
	
	# how many follow you
	followers = 0
	try:
		thatMany = Follow.objects.filter(personOfAttention = personOfAttention)
		followers = len(thatMany)
	except (Follow.DoesNotExist, AttributeError):
		pass
	
	# how many you follow
	following = 0
	try:
		thatMany = Follow.objects.filter(follower = personOfAttention)
		following = len(thatMany)
	except (Follow.DoesNotExist, AttributeError):
		pass
	
	toJSON = {
	"username": username,
	"followingThisOne": followingThisOne,
	"followers": followers,
	"following": following,
	}
	return JsonResponse(toJSON, status=200)
	
def userInfo(request):
	return JsonResponse({"user": str(request.user), "isAnonymous": request.user.is_anonymous}, status=200)

network/templates/network/index.html
{% extends "network/layout.html" %}
{% load static %}

{% block body %}
<div id = "userSpace"></div>
<div id = "newPost">
    <div class = "headline">● New Message ●</div>
    <form style="text-align: center;">
        <textarea id="postTextarea" placeholder="What do you want to share..."></textarea>
        <div style="display: flex; align-items: center; justify-content: center;">
        	<div class = "pearl"></div>
        	<input type="submit" id="postSubmit" value="" style="width: 50px; height:50px; border-radius: 25px;margin:20px;"></input>
        	<div class = "pearl"></div>
        </div>
    </form>
</div>
<div class = "headline" id = "postsHeadline"></div>
<div id = "verticalFrame">
	<div style ="display:flex; justify-content: center;">
		<div class = "pearl2"></div>
		<div style="width: 470px;"></div>
		<div class = "pearl2"></div>
	</div>
	<div id = "posts"></div>
	<div style ="display:flex; justify-content: center;">
		<div class = "pearl2"></div>
		<div style="width: 470px;"></div>
		<div class = "pearl2"></div>
	</div>
</div>
<div id = "pagination"></div>
<script src="{% static 'network/index.js' %}"></script>
<script> document.querySelector('#allPosts').style.display = 'block'; </script>
{% endblock %}

network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Social Network{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'network/styles.css' %}" rel="stylesheet">
        
        <link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Crimson+Pro:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
           <a class="nav-link" style="color:#002e3f; font-weight: 600;" href="{% url 'network:index' %}">NETWORK</a>
            <div>
              <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" id = "user">{{ user.username }}</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" id = "allPosts" >All Messages</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" id = "following">Following</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>
        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

network/templates/network/login.html
{% extends "network/layout.html" %}
{% block body %}
<div class = "login">
	<h2>Login</h2>
    {% if message %}
        <div>{{ message }}</div>
    {% endif %}
    <form action="{% url 'network:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>
    Don't have an account? <a href="{% url 'network:register' %}">Register here.</a>
</div>
<script> document.querySelector('#allPosts').style.display = 'none'; </script>
{% endblock %}

network/templates/network/register.html
{% extends "network/layout.html" %}
{% block body %}
<div class = "login">
	<h2>Register</h2>
    {% if message %}
        <div>{{ message }}</div>
    {% endif %}
    <form action="{% url 'network:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>
    Already have an account? <a href="{% url 'network:login' %}">Log In here.</a>
</div>
<script> document.querySelector('#allPosts').style.display = 'none'; </script>
{% endblock %}